name: 'vault'
version: '1.0.5'
usage: 'get-common, upgrade-common, and delete-common'
description: |-
  A Helm plugin for managing VaultStaticSecret resources.
ignoreFlags: false
useTunnel: false
command: '$HELM_PLUGIN_DIR/bin/helm-vault'
hooks:
  install: 'cd $HELM_PLUGIN_DIR; ./scripts/install.sh'
  update: 'cd $HELM_PLUGIN_DIR; ./scripts/install.sh'
